name: Build All

on:
  push:
    branches-ignore:
      - publish-docs

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { binary-version: "2.12", java-version: "adopt@1.8" }

    steps:
    - uses: actions/checkout@v4
    - uses: olafurpg/setup-scala@v14
      with:
        java-version: ${{ matrix.scala.java-version }}

    - name: Cache SBT
      uses: actions/cache@v3
      with:
        path: |
          ~/.ivy2/cache
          ~/.cache/coursier
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-

    - name: Build for Scala ${{ matrix.scala.version }} and sbt ${{ matrix.scala.sbt-version }}
      run: |
        java -version
        .github/workflows/sbt-build-simple.sh
