name: Build All

on:
  push:
    branches-ignore:
      - publish-docs

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { binary-version: "2.12", java-version: "11", java-distribution: "temurin" }

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.scala.java-version }}
        distribution: ${{ matrix.scala.java-distribution }}
        cache: 'sbt'
    - uses: sbt/setup-sbt@v1

    - name: Build for Scala ${{ matrix.scala.version }} and sbt ${{ matrix.scala.sbt-version }}
      run: |
        java -version
        .github/workflows/sbt-build-simple.sh
