name: Build All

on:
  push:
    branches-ignore:
      - publish-docs

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { version: "2.12.12", binary-version: "2.12", java-version: "adopt@1.8", sbt-version: "1.4.9" }

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: ${{ matrix.scala.java-version }}

    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.cache/coursier
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
        restore-keys: |
          ${{ runner.os }}-sbt-${{ matrix.scala.binary-version }}-

    - name: Build for Scala ${{ matrix.scala.version }} and sbt ${{ matrix.scala.sbt-version }}
      run: |
        java -version
        .github/workflows/sbt-build-simple.sh ${{ matrix.scala.version }} ${{ matrix.scala.sbt-version }}
