name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { version: "2.12.12", java-version: "8", sbt-version: "1.3.13" }

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.scala.java-version }}

    - name: sbt GitHub Release sbt-github-pages
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_AUTH_TOKEN_GITHUB }}
      run: |
        echo "Run] sbt GitHub release"
        echo 'sbt -J-Xmx2048m ++${{ matrix.scala.version }}! ^^${{ matrix.scala.sbt-version }} clean test packagedArtifacts'
        sbt -J-Xmx2048m \
          ++${{ matrix.scala.version }}! \
          ^^${{ matrix.scala.sbt-version }} \
          clean \
          test \
          packagedArtifacts
        echo "====================="
        echo 'sbt -J-Xmx2048m ++${{ matrix.scala.version }}! ^^${{ matrix.scala.sbt-version }} gitHubRelease'
        sbt -J-Xmx2048m \
          ++${{ matrix.scala.version }}! \
          ^^${{ matrix.scala.sbt-version }} \
          gitHubRelease

  publish:
    needs: build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { version: "2.12.11", binary-version: "2.12", java-version: "8", sbt-version: "1.3.13" }

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.scala.java-version }}

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-scala-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-coursier-scala-${{ matrix.scala.binary-version }}-

      - name: Cache Ivy
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-scala-${{ matrix.scala.binary-version }}-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/build.properties') }}
          restore-keys: |
            ${{ runner.os }}-ivy-scala-${{ matrix.scala.binary-version }}-

      - name: sbt Publish sbt-github-pages
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        run: |
          echo "Run] sbt publish for Scala ${{ matrix.scala.version }}"
          echo 'sbt -J-Xmx2048m ++${{ matrix.scala.version }}! ^^${{ matrix.scala.sbt-version }} -v clean publish"'
          sbt -J-Xmx2048m \
            ++${{ matrix.scala.version }}! \
            ^^${{ matrix.scala.sbt-version }} \
            -v \
            clean \
            publish
          echo "====================="
